# Generated by Django 6.0.5 on 2026-06-06 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='sources',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='context_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='last_recommended_breeds',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='last_user_preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='RecommendationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breeds', models.JSONField(blank=True, default=list)),
                ('user_preferences', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_results', to='chatbot.chatmessage')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_results', to='chatbot.chatsession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
